# Generated by Django 4.0.3 on 2022-04-05 21:17

import app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('n_id', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14, 'الرقم القومى يجب ان يكون 14 رقم'), app.models.only_int])),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(11, 'رقم الهاتف يجب ان يكون 11رقم'), app.models.only_int])),
                ('home_number', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(7, 'رقم هاتف المنزل يجب ان يكون 7 ارقام'), app.models.only_int])),
            ],
            options={
                'unique_together': {('n_id', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('n_id', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14, 'الرقم القومى يجب ان يكون 14 رقم'), app.models.only_int])),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(11, 'رقم الهاتف يجب ان يكون 11رقم'), app.models.only_int])),
                ('home_number', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(7, 'رقم هاتف المنزل يجب ان يكون 7 ارقام'), app.models.only_int])),
            ],
            options={
                'unique_together': {('n_id', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session', to='app.day')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='app.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='app.teacher')),
            ],
            options={
                'unique_together': {('day', 'time', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الموظف')),
                ('n_id', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14, 'الرقم القومى يجب ان يكون 14 رقم'), app.models.only_int], verbose_name='الرقم القومى')),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(11, 'رقم الهاتف يجب ان يكون 11رقم'), app.models.only_int])),
                ('home_number', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(7, 'رقم هاتف المنزل يجب ان يكون 7 ارقام'), app.models.only_int])),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('n_id', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='StudentSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_session', to='app.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_session', to='app.student')),
            ],
            options={
                'unique_together': {('student', 'session')},
            },
        ),
    ]
