# Generated by Django 4.0.3 on 2022-04-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='app.room'),
        ),
    ]
