# Generated by Django 4.0.3 on 2022-04-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
