# Generated by Django 4.0.3 on 2022-05-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_manager_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sessions',
            field=models.ManyToManyField(related_name='sessions', to='app.session'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='student_teacher', to='app.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room', to='app.room'),
        ),
        migrations.AlterField(
            model_name='session',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to='app.teacher'),
        ),
    ]
