# Generated by Django 4.0.3 on 2022-05-24 13:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0006_remove_student_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('session_date', models.DateField(default=datetime.date.today)),
                ('report', models.TextField(blank=True, max_length=125, null=True)),
                ('review_report', models.TextField(blank=True, max_length=125, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_report', to='app.session')),
            ],
            options={
                'unique_together': {('session', 'session_date')},
            },
        ),
        migrations.CreateModel(
            name='StudentReporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.CharField(blank=True, choices=[('حضور', 'حضور'), ('غياب', 'غياب')], default='لم يتم التحديد', max_length=15, null=True)),
                ('money', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('session_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_session_report', to='reports.sessionreporter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_report', to='app.student')),
            ],
        ),
    ]
