# Generated by Django 4.0.3 on 2022-05-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_student_sessions'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentreporter',
            unique_together={('student', 'session_report')},
        ),
    ]
